jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.9"

      - name: Install pipenv
        run: pip install pipenv

      - name: Sync dependencies
        working-directory: EDCBNotifier
        env:
          PIPENV_VENV_IN_PROJECT: "true"
        run: pipenv sync

      - name: Build exe
        working-directory: EDCBNotifier
        run: pipenv run build

      - name: Upload exe
        uses: actions/upload-artifact@v4
        with:
          name: EDCBNotifier-exe
          path: |
            EDCBNotifier/dist/*.exe